name = "code"
uuid = "5bb208b6-26a0-44f3-a20c-bf9107d67908"
authors = ["Tanya Strydom <tanya.strydom@icloud.com>"]
version = "0.1.0"

[deps]
SpeciesInteractionNetworks = "49e116ef-912f-4766-9e56-896a49944adc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
SpeciesInteractionNetworks = "0.0.1"
Statistics = "1.11.1"
